version: "3.9"

services:

  silvertracker:
    build: .
    container_name: silvertracker
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/silvertracker
    env_file:
      - contrib/.env-docker