# Generated by Django 5.0.2 on 2024-02-12 23:43

import django.core.validators
import django.db.models.deletion
import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('cpf', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome_produto', models.CharField(max_length=255)),
                ('unidade', models.CharField(blank=True, choices=[('unidade', 'Unidade'), ('par', 'Par')], max_length=10, null=True)),
                ('tipo', models.CharField(choices=[('anel', 'Anel'), ('colar', 'Colar'), ('brinco', 'Brinco'), ('cordao', 'Cordão'), ('tornozeleira', 'Tornozeleira'), ('pulseira', 'Pulseira'), ('outros', 'Outros')], max_length=20)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saldo_estoque', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_entrada', models.CharField(max_length=50)),
                ('tipo_movimento', models.CharField(choices=[('compra', 'Compra'), ('ajuste', 'Ajuste de Inventário'), ('devolucao', 'Devolução')], max_length=20)),
                ('nf', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'fornecedor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'db_table': 'entrada_produto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('debito', 'Débito'), ('credito', 'Crédito'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('desconto_maquina', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('total_parcial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.venda')),
            ],
            options={
                'db_table': 'item_venda',
            },
        ),
    ]
