# Generated by Django 5.0.2 on 2024-02-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('anel', 'Anel'), ('brinco', 'Brinco'), ('colar', 'Colar'), ('cordao', 'Cordão'), ('pingente', 'Pingente'), ('pulseira', 'Pulseira'), ('tornozeleira', 'Tornozeleira'), ('outros', 'Outros')], max_length=20),
        ),
    ]
