# Generated by Django 5.0.2 on 2024-02-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='foi_pago',
            field=models.BooleanField(default=True),
        ),
    ]
