# Generated by Django 5.0.2 on 2024-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venda_foi_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
