# Generated by Django 5.0.2 on 2024-02-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_esta_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conta', models.CharField(max_length=255, unique=True)),
                ('total_investido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_vendido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lucro_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lucro_livre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investimento_amortizado', models.BooleanField(default=False)),
                ('parcial_conta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conta',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('compra_produtos', 'Compra de Produtos'), ('compra_suprimentos', 'Compra de Suprimentos'), ('pagamento_conta', 'Pagamento de Conta'), ('prolabore', 'Pró-labore'), ('outras_retiradas', 'Outras Retiradas')], max_length=20)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_despesa', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
        migrations.CreateModel(
            name='EntradaCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(choices=[('aporte_financeiro', 'Aporte Financeiro'), ('emprestimo', 'Empréstimo')], max_length=20)),
                ('tipo_investimento', models.CharField(choices=[('proprio', 'Próprio'), ('terceiros', 'Terceiros')], max_length=20)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrada_capital',
            },
        ),
    ]
